# Generated by Django 6.0.2 on 2026-02-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
